### ISSUE TITLE
Write documentation

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#1]
Better documentation of the workflow is required to ensure end-users can easily run the scripts as intended.

**Comment by mattjmeier** [comment]
Need to make sure to include direction on environment setup and pre-requisites to run workflows. Required environment variables for the Snakemake workflow, and maybe some guidance or even provide a containerized version or commands to run to create the required environment.

**Comment by cookkate** [comment]
Also, we should describe what's required in the metadata files.

**Comment by mattjmeier** [comment]
@LMBradford  close this whenever you're happy, the README is in pretty decent shape

**Comment by LMBradford** [comment]
The README will keep getting updated as we go along, but I don't think it needs to be an open issue...it's not like it's ever going to be 100% done!
