### ISSUE TITLE
Configuration to prevent CPM-based filtering of genes before DESeq2

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#12]
This bit of code is used before running DESeq2:

`dds <- dds[rowSums(counts(dds)) > 1])`

But for biomarker applications (and probably for other reasons) we need to include everything sometimes; even genes that are not quantified.

I think the solution is to **exclude** this code by default. However, for whole-transcriptome experiments (both TempO-Seq and RNASeq) DESeq2 can take a very long time to run if you don't filter those basically absent genes first. Exacerbated by experiments with hundreds of samples. So, maybe adding something to the config to allow it to run this way.

**Comment by cookkate** [comment]
Will be fixed by #5
