### ISSUE TITLE
DEG list output

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#130]
We are currently putting the DEG summary list into every subfolder for each facet, which doesn't make sense really for the summary file across all facets (*-DEG_summary.txt). We should probably put it in the folder above, just once. This is probably determined in the write_output_tables script but haven't looked yet.

edited for clarity

**Comment by cookkate** [comment]
Yeah should move that code from write_output_tables.R to summarize_across_facets.R

As a separate issue, summarize_across_facets.R needs to be cleaned up, and I want to make it a proper report instead of some random pngs.
