### ISSUE TITLE
MultiQC doesn't work with Python 3.12

### ISSUE THREAD

**Issue by LMBradford** [R-ODAF/R-ODAF_Health_Canada#158]
See discussion: https://stackoverflow.com/questions/77274572/multiqc-modulenotfounderror-no-module-named-imp

It works when python is downgraded to 3.11 in conda environment.

Will add python=3.11 in yaml env file.

**Comment by mattjmeier** [comment]
That's unfortunate, thanks for noticing.

I recall that we have frozen the version of multiqc as well because of some other problem. I wonder if we should try using a newer version now.

**Comment by LMBradford** [comment]
The developers know about the problem and promise it will be addressed in the next MultiQC version https://github.com/ewels/MultiQC/issues/2112. Maybe we should work around the problem for now (downgrade python to 3.11?) and leave an open issue to remind us to move to the newer MultiQC version when available?

**Comment by LMBradford** [comment]
> @LMBradford, the new version of MultiQC that supports 3.12 is released now :) https://github.com/ewels/MultiQC/releases/tag/v1.17

Amazing, thank you!
