### ISSUE TITLE
Report organization

### ISSUE THREAD

**Issue by cookkate** [R-ODAF/R-ODAF_Health_Canada#49]
The current DEseq results report is getting too long to be effective and the file size has ballooned due to all the embedded data. I propose splitting it into multiple reports. In general, there will be one report per facet, except for the summary report.

(0. QC report. Not part of this discussion)
1. Summary report (to be developed): a summary table of the #DEGs per facet. What else?
2. Main DEG report
  - intro QC paragraph
  - Sample data tables?
  - read count boxplots
  - DEG summary table
  - PCA (all genes/DEGs only/top 100 most variable)
  - heatmaps (which heatmaps should be kept?)
  - MA plots
  - volcano plots
  - P-value distribution plots (is the table necessary or can we cut that?)
  - top 20 gene plots? Are these useful?
3. GO & pathway analysis
  - as before, but split off into a separate report
4. data explorer report
  - significant DEG searchable table
  - gene-level plots

All reports should include the session info chunk.

**Comment by mattjmeier** [comment]
Agree with this, as you know. Here are my thoughts on the "ideal" groupings of analyses:

# Study-wide
  0. QC report. Not part of this discussion, agreed
  1. MultiQC report - also study-wide
  2. Summary report - can keep this pretty simple I think - the table showing DEGs across the study, and maybe also summarize that in a plot? I think the QC report, once tackled separately, and combined with the MultiQC report on the sequence data, should provide a really comprehensive "study-level" what might someone want to know... read counts, etc, etc.

# Faceted reports
  1. Main DEG report: this could be re-ordered and modified substantially... current numbers in parantheses for comparison
    - Volcano plots (14) -- gives a good high level summary at a glance
    - Genes of interest (13) -- often one the first things I'll look at myself... it shows upfront any big trends and whether genes you recognize are where they should be
    - Gene-level plots for top 20 features -- maybe we could cut this to 10, since we will have the data exploration plot. Maybe even make it a tabset? I do like having it myself because it gives granularity at the sample level - how much spread is in the data... are dose-response trends looking reasonable or not across doses...
    - Heatmaps (18) -- I also like these but would consider dropping the row variance based one entirely, because I think it can be misleading
    - PCA (16) -- people like to see how the data clusters, same with the item below, useful to have but not so exciting that it needs to be upfront
  2. What about a supplementary "stats for nerds" report?
    - where we could shunt the p-value distribution, MA plots, and sample-to-sample distances? I know many PIs like those last ones but I think PCA is just as informative - and we aren't dropping the analysis altogether... up for discussion though.
    - hard to decide on because while I don't always pay too much attention to these things, the p value distribution can be pretty informative from time to time, and you don't want to necessarily ignore it, so it's always a good idea to look through all of this.
  3. Pathway  analysis - agree, keep it the same for now
  4. Data explorer report - agree, your idea for this is perfect, searchable gene plots and searchable DEG table

**Comment by cookkate** [comment]
>  I think the QC report, once tackled separately, and combined with the MultiQC report on the sequence data, should provide a really comprehensive "study-level" what might someone want to know... read counts, etc, etc.

Sorry, are you suggesting that we extract some of that and put it in the DEG summary report or that the DEG summary report should be a bare-bones count of # DEGs/facet? (I suggest the latter)

I agree with all of the rest of your suggestions! Shouldn't be too difficult to do.

**Comment by cookkate** [comment]
I wonder if there's a set of genes that we frequently see reacting in these experiments that might be worth looking at every time? What about markers of cell death? Worth asking scientists for any favourite genes they want to look at at the start, that we can include as a parameter?

**Comment by cookkate** [comment]
Fixed by #16
