### ISSUE TITLE
scripts/temposeq/TempO-SeqR_v3.1.R line 73

### ISSUE THREAD

**Issue by johndhstead** [R-ODAF/R-ODAF_Health_Canada#56]
The following line was causing the pipeline to terminate:

cores <- floor(num_clusters/7)

If threads/CPU is set to <7, the above gives a value of zero. (Running with 4 cores, changing this to:

cores <- floor(num_clusters/4)

allowed the code to run successfully. Might be a good place for an either/or option to permit running of lower powered local machines

thanks!

**Comment by cookkate** [comment]
This one should also be fixed by e71adee. Please reopen this if it's not but I think we should be good.
