### ISSUE TITLE
scripts/temposeq/TempO-SeqR_v3.1.R: Line 176

### ISSUE THREAD

**Issue by johndhstead** [R-ODAF/R-ODAF_Health_Canada#57]
I was receiving a 'Killed' error when running the pipeline, associated with line 176:

cnt <- qCount(proj2, txStart, clObj = cl)

This was fixed by changing the code to:

cnt <- qCount(proj2, txStart)

The cause was likely either trying to run with too few cores or with insufficient RAM (I was running within Docker with 8 cores and 8 Gb RAM. The Killed message is characteristic of exceeding the processing limit of the Docker container). Not sure what a good route would be for a fix - I simply change the code whenever I run the pipeline

**Comment by cookkate** [comment]
This is due to the TempOSeqR script being written to be able to work with a cluster. I've rewritten it to work with Snakemake and taken out those lines (commit e75adee). If you pull the most recent version of main it should be fixed.
