### ISSUE TITLE
Rmd/DESeq2_report.rnaseq.Rmd Line 363

### ISSUE THREAD

**Issue by johndhstead** [R-ODAF/R-ODAF_Health_Canada#58]
I encountered sporadic issues connecting to the Ensembl database. This may have been unlucky (mirrors were responding poorly over 48 hours?). I changed the code from...

# Line 363: 
tryCatch({
  ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "uswest.ensembl.org")
}, error = function(err){
     ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "useast.ensembl.org")
}, finally={
    if (is.null(ensembl)) {stop("Can't connect to Ensembl!")}
})

to....

tryCatch({
  ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "https://www.ensembl.org")
}, error = function(err){
     ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "http://uswest.ensembl.org/")
}, error = function(err){
     ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "http://useast.ensembl.org/")
}, error = function(err){
     ensembl <- useMart("ensembl",
                     dataset = ensembl_species,
                     host = "http://asia.ensembl.org/")
}, finally={
    if (is.null(ensembl)) {stop("Can't connect to Ensembl!")}
})

I was still experiencing some issues (need to keep testing). However, the above code does fix a warning received in the original code, that ensembl will soon be requiring the full http:// address on the host mirrors

**Comment by cookkate** [comment]
Matt and I have also had transient issues with Ensembl. We're working to reduce our dependence on it. In theory useMart should be making multiple attempts with different servers, but wrapping that in our own multiple attempts should help as well. And thanks for catching the http:// thing.
