### ISSUE TITLE
Clean up file structure

### ISSUE THREAD

**Issue by cookkate** [R-ODAF/R-ODAF_Health_Canada#6]
Posting this to get on the same page about file structure for the pipeline. Please comment if you have any suggestions.

Snakemake has a [recommended](https://snakemake.readthedocs.io/en/stable/snakefiles/deployment.html) file structure. I based this partly on that.

```├── .gitignore
├── README.md
├── LICENSE.md
├── data
│   ├── raw
│   ├── processed
│   │  ├── trimmed
│   │  ├── aligned
│   │  └── quant
│   └── metadata
├── workflow
|   └── Snakefile
├── scripts
│   ├── run_DEseq.R
|   ├── temposeq
│   │  └── temposeq_scripts.R
├── Rmd
│   ├── Sample_QC.Rmd
|   └── DESeq2_report.rnaseq.Rmd
├── config
│   ├── config.yaml
│   └── some-sheet.tsv
├── logs
│   └── log-alignment-DATE.txt
├── results
│   ├── QC
│   │  ├── multiqc_report.html
│   │  ├── multiqc_data.zip
│   │  └── Sample_QC.html
│   ├── DEG_output
│   └── BMD
└── reports```

**Comment by mattjmeier** [comment]
I've looked this over and it all seems reasonable.

Obviously some lightweight toy datasets for testing will help when making changes like this... stay tuned, will be working on that this week I hope.

**Comment by mattjmeier** [comment]
Not sure if this change in the PRs you're working on now, but it seems like we could do this easily (i.e., moving BMD/biomarker files, DEG output, MultiQC all into a results or analysis folder, whichever).

We can clean up some of the outputs as well... there are some superfluous things produced at the moment that we can either stop producing altogether or throw in a "details" folder or some such thing. E.g., in DEG_output there is a lot of redundant stuff... txt files that have the same information as the Excel files - now I think it's good to keep both, but for data handoff, it makes more sense to consolidate everything for a drag-and-drop.

**Comment by mattjmeier** [comment]
Now that we've merged that PR... Are we happy enough with the file structure to close this issue, or should we make any other changes?

**Comment by cookkate** [comment]
I think so!
