### ISSUE TITLE
Magical disappearing and reappearing params list

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#7]
Need to fix the occasional appearance of a list of parameters from YAML frontmatter at the beginning of HTML reports. Cannot seem to find anything similar after a quick google search. No idea why the problem could be intermittent. It is *only* the params that are getting printed and nothing else from the YAML.

**Comment by mattjmeier** [comment]
I re-analyzed the same data and the problem seems to have fixed itself again. Will monitor this with more testing...

**Comment by mattjmeier** [comment]
I still have no idea why this happens sometimes. I've seen it in reports for one chemical but not another within the **same** set of reports!!

**Comment by mattjmeier** [comment]
Fixed by a6c5ff15865285459bc00a2b037e1d68e03f5fde.

Turns out I just needed to put the title and subtitle ahead of the output... duh.

**Comment by mattjmeier** [comment]
Ok. There is another reason this can happen - if you specify in the params, for example, `"\t"` for the separator, that escape character does something funny. Either I'm using the wrong syntax to pass that as a string via YAML or we just shouldn't be doing that at all. It kind of needs to be configurable... but obviously we can't have this issue screwing up the formatting.

I would suggest that we instead find a "smart" function that can determine the separator value before/during data import.

**Comment by cookkate** [comment]
Ok that's a super weird bug.

**Comment by mattjmeier** [comment]
Closing this since we are now just assuming that TempOSeq will have a CSV for import by default, and RNASeq will have a TSV. Not ideal but I don't see another easy way given the lack of functions available to automatically determine the separator.
