### ISSUE TITLE
Sample name replacement in MultiQC report

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#72]
[Sample renaming](https://multiqc.info/docs/#bulk-sample-renaming-in-reports) doesn't quite work right. It uses partial substring matches, which, depending on how the metadata table looks, can be a disaster. I don't know why it doesn't automatically use exact matches. I don't know if there is a way to change this - might need to open an issue in MultiQC.

Just a minor thing, but it bugs me when I want to look at sample groupings in the report!

**Comment by LMBradford** [comment]
This seems to have been a problem with the browser and as far as I can tell it's working properly now.
