### ISSUE TITLE
Minor tweaks needed for summarize_across_facets.R

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#81]
I realized that the contrasts are not ordered by params$sortcol... is there a way we can maintain that structure here? I've lost track of what would be available in the environment. It seems like it should be possible.

Otherwise, the plot can be very misleading, and not sorted by dose (had a slight panic attack when reviewing some data!)

**Comment by cookkate** [comment]
Whoops, yeah, that's totally doable. I'll do it tomorrow morning.

**Comment by mattjmeier** [comment]
Oh cool, thanks. Sorry this is tied to your Gmail... Didn't mean to bug you after hours!! Talk to you tomorrow.

**Comment by cookkate** [comment]
It's ok I'm good at ignoring them :)

**Comment by cookkate** [comment]
Just to double check, my intention is to have the labels ordered by facet, and then by dose within that facet. Does that work?
