### ISSUE TITLE
Heatmaps - I am getting NA : geneXYZ (not sure where the NA comes from)

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#82]
Heatmap labels seem to have an NA in them for some datasets...

**Comment by cookkate** [comment]
Ok this seems to be an issue of features (ensembl gene IDs) that are associated with loci without an assigned symbol, but which do have GM IDs or something like that. So the solution will be filling in the alternate ID if no symbol is available.

**Comment by mattjmeier** [comment]
Fixed by #115 and #117
