### ISSUE TITLE
Genes of interest (4.1) - there is a warning shown; and also this figure is a bit tall by default.

### ISSUE THREAD

**Issue by mattjmeier** [R-ODAF/R-ODAF_Health_Canada#85]
In addition to being tall by default, these contrasts aren't sorted by params$sortcol

**Comment by mattjmeier** [comment]
Deseq2 does create padj of na for various reasons... The one I'm aware of
was cook's distance but we aren't using that

**Comment by cookkate** [comment]
I looked it up and it says that independent p-value filtering creates NA for nonsignificant values. I think I found the spot where those used to be filtered out and aren't in the new script so should be fixed, just gotta test.

**Comment by mattjmeier** [comment]
👍

**Comment by cookkate** [comment]
???
